---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nats
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nats
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: my-nats
  targetNamespace: default
  upgrade:
    crds: CreateReplace

