apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: devopswithk8s-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/shenranwang/devopswithk8s
  ref:
    branch: main
